application: kercrypt
version: 1
runtime: python
api_version: 1

handlers:
- url: /gwtcipher
  static_dir: ../war/gwtcipher

- url: /GWTCipher.css
  static_files: GWTCipher.css
  upload: ../war/GWTCipher.css

- url: .*
  static_files: GWTCipher.html
  upload: ../war/GWTCipher.html
